Level.create!([
  {rank: 0, num_hours: 0, num_places: 0, num_sponsors: 0, num_catches: 0},
  {rank: 1, num_hours: 0, num_places: 0, num_sponsors: 0, num_catches: 0},
  {rank: 2, num_hours: 5, num_places: 1, num_sponsors: 0, num_catches: 0},
  {rank: 3, num_hours: 10, num_places: 3, num_sponsors: 2, num_catches: 1},
  {rank: 4, num_hours: 20, num_places: 6, num_sponsors: 4, num_catches: 3},
  {rank: 5, num_hours: 50, num_places: 10, num_sponsors: 6, num_catches: 6},
  {rank: 6, num_hours: 100, num_places: 20, num_sponsors: 8, num_catches: 10}
])

Hashtag.create!([
  { name: "TutorenBild",            level: Level.find_by( rank: 0), points: 20, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Bild von deinen Tutoren",                                                                  description: "Bestenfalls haben deine Tutoren schon ein Bild von sich hochgeladen bevor ihr eure Gruppe sucht. Es sind nur die Tutoren auf diesem Bild nötig, die Mindestanzahl von 3 Personen pro Bild gilt hier nicht. "},
  { name: "GruppenBild",            level: Level.find_by( rank: 0), points: 50, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Macht ein Bild von eurer Gruppe",                                                          description: "Je ausgefallener die Bilder sind desto besser. Sorgt bei grade beim Gruppenbild dafür das alle eure Teammitglieder auf dem Bild sind. Abgesehen von genannten Ausnahmen müssen auf allen Bildern mindestens 3 Teammitglieder zu sehen sein. "},
  { name: "Essen",                  level: Level.find_by( rank: 1), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Gemeinsames Essen oder Kochen",                                                            description: "Wiederholbar"},
  { name: "Spielen",                level: Level.find_by( rank: 1), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Spielt IRGENDEIN Spiel zusammen",                                                          description: "Wiederholbar; z.B. Spielefiebel S.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              48:        Hahnenkampf. "},
  { name: "SuperC",                 level: Level.find_by( rank: 1), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "Schmachtenburg",         level: Level.find_by( rank: 1), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "Ponttor",                level: Level.find_by( rank: 1), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "HennigsHorde",           level: Level.find_by( rank: 2), points: 3,  category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Findet so viele Horde-Sticker wie möglich",                                                description: "Wiederholbar; Lustige Gruppenbilder gemeinsam mit den Stickern& erkennbaren Ort des Stickers sind die besten Bilder. Die Mindestanzahl von 3 Personen pro Bild gilt hier nicht. "},
  { name: "Institutsführung",       level: Level.find_by( rank: 1), points: 40, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Geht auf jeden Fall zu der Institutsführung die euch zugeteilt sind. ",                    description: "Die Institute machen sich extra Arbeit nur um euch die Institute zu zeigen also nehmt diesen Termin mit allen Gruppenmitgliedern wahr."},
  { name: "GrillplatzRütscherstr.", level: Level.find_by( rank: 2), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto an diesem Ort",                                                             description: ""},
  { name: "Tutorenversorgung",      level: Level.find_by( rank: 2), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Versorgt eure Tutoren mit Getränken",                                                      description: "Wiederholbar; Ihr könnt euch bei euren Tutoren jederzeit mit einem Kalt oder Warmgetränk für ihre Expertise im Stadt kennenlernen bedanken"},
  { name: "Rathaus",                level: Level.find_by( rank: 2), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "Dom",                    level: Level.find_by( rank: 2), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "EtiSticker",             level: Level.find_by( rank: 3), points: 5,  category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Entfernt die blauen kleinen Eti-Sticker",                                                  description: "Wiederholbar; Lustige Gruppenbilder gemeinsam mit den Stickern& erkennbaren Ort des Stickers sind die besten Bilder. Die Mindestanzahl von 3 Personen pro Bild gilt hier nicht. "},
  { name: "MediSticker",            level: Level.find_by( rank: 3), points: 5,  category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Entfernt die grünen runden Medi-Sticker",                                                  description: "Wiederholbar; Lustige Gruppenbilder gemeinsam mit den Stickern& erkennbaren Ort des Stickers sind die besten Bilder. Die Mindestanzahl von 3 Personen pro Bild gilt hier nicht. "},
  { name: "RWTHOnlineSchulung",     level: Level.find_by( rank: 3), points: 20, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Besucht eure Schulungen",                                                                  description: "Die Schulungen sind sehr hilfreich um sich in den Onlinesystemen auszukennen. Inhalt ist Klausurrelevant!!"},
  { name: "Natur",                  level: Level.find_by( rank: 3), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Geht mal in die Natur.",                                                                   description: "Wiederholbar; Erkundet die Grünflächen in und um Aachen. Aber hinterlasst keinen Müll und benehmt euch"},
  { name: "Pyjamaparty",            level: Level.find_by( rank: 3), points: 20, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Übernachtet gemeinsam irgendwo.",                                                          description: "Wiederholbar; Egal ob jemand noch keine Wohnung hat, zu weit weg wohnt und ihr ihm einen Schlafplatz bietet oder ihr eine Sleepoverparty macht. Die Mindestanzahl von 3 Personen pro Bild gilt hier nicht."},
  { name: "AusSicherheitsgründen",  level: Level.find_by( rank: 3), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Überall wo man das Sagen Kann",                                                            description: "Wiederholbar; Macht etwas wozu man sagen kann aus Sicherheitsgründen. Jemanden Abends heim bringen, beim Fahrradfahren Warnwesten und Helm tragen... werdet Kreativ"},
  { name: "Humba",                  level: Level.find_by( rank: 3), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Gesänge anstimmen",                                                                        description: "Ob Humba oder ein anderes freundliches Lied könnt ihr an dieser Stelle alles Singen."},
  { name: "MüllAufheben",           level: Level.find_by( rank: 4), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Macht es besser als die vor euch und Entfernt Müll",                                       description: "Wiederholbar; Damit nicht nur die Fachschaft, das ESA- Team und die Stadt euch hinterherräumen werdet selber mal aktiv und hinterlasst die Orte wo ihr wart sauberer als vorher."},
  { name: "KüstümGehtImmer",        level: Level.find_by( rank: 4), points: 20, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Überlegt euch ein Gruppenkostüm/Motto",                                                    description: "Wiederholbar; In einer Gruppe ein Kostüm tragen wirkt Wunder beim Gruppenzusammenhalt."},
  { name: "VollerFarbkreis",        level: Level.find_by( rank: 4), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Macht Bilder mit den verschiedenfarbigen Tutoren anderer Fachschaften",                    description: "Wiederholbar; Findet im Rahmen der Erstiwoche alle Farben der verschiedenen Fachschaften. Für jede Farbe kann ein Bild gemacht werden."},
  { name: "Asta",                   level: Level.find_by( rank: 2), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "MaschiPartySchlange",    level: Level.find_by( rank: 4), points: 30, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Ist für jeden Maschi ein muss",                                                            description: "Wenn ihr dann noch rein kommt um so besser."},
  { name: "KaterTag",               level: Level.find_by( rank: 5), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Geteiltes Leid ist halbes Leid",                                                           description: "Wiederholbar; Verbringt den Tag, an dem ihr euch von den Strapazen der anstrengenden Woche erholt habt gemeinsam. Top Auswahl an Filmen sind \"Findet Nemo\" und \"Frozen\""},
  { name: "Gratis",                 level: Level.find_by( rank: 5), points: 5,  category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Teilt eurem Team mit wenn es was umsonst gibt",                                            description: "Wiederholbar; Wenn Erstitüten verteilt werden oder es sonst etwas kostenlos gibt."},
  { name: "Mensa",                  level: Level.find_by( rank: 3), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "Fachschaft",             level: Level.find_by( rank: 6), points: 20, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "Bushof",                 level: Level.find_by( rank: 2), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "UKA",                    level: Level.find_by( rank: 3), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "Theater",                level: Level.find_by( rank: 5), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto mit dem Gebäude",                                                           description: ""},
  { name: "HängemattenLouisberg",   level: Level.find_by( rank: 6), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto an diesem Ort",                                                             description: ""},
  { name: "3-LänderEck",            level: Level.find_by( rank: 6), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Mache ein Foto an diesem Ort",                                                             description: ""},
  { name: "Blutspenden",            level: Level.find_by( rank: 6), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Blut ist immer eine Mangelware",                                                           description: "Geht gemeinsam mit eurer Gruppe regelmäßig Blutspenden. Dadurch erinnert ihr euch Gegenseitig daran und ihr geht öfter."},
  { name: "Hüpfen",                 level: Level.find_by( rank: 6), points: 10, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Besucht den Beliebtesten Kurs im HSZ",                                                     description: "Erfahrt durch die Buchung und Besuchung des Kurses \"Fitness mit Musik\" den Ablauf eines Sportkurses. Informiert euch über das vielfältige Sportangebot des Hoschschul Sport Zentrums"},
  { name: "KuchenFürCharlotte",     level: Level.find_by( rank: 6), points: 50, category: nil,    repeat_time: nil, start_date: nil, picture: nil, info: "Heute ist Charlottes Geburstag",                                                           description: "Bringt ihr möglichst bald einen Kuchen in die Fachschaft und bedankt euch für ihre Arbeit in der Erstiwoche. Kuchen geht zu jeder Mahlzeit."},
  { name: "Florian",                level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Geschäftsführer",                                                                          description: "Hey Maschis, mein Name ist Florian und man kennt mich womöglich schon aus dem letzten Fachschaftsrat, welcher mir super Spaß gemacht hat. Da hatte ich direkt Lust auf die zweite Runde, nun als euer Geschäftsführer für das Ratsjahr 2019/2020. Meine Aufgabe ist es, die Abläufe in der Fachschaftsarbeit zu koordinieren. Dafür unterstütze ich meine Koordinatoren, Referenten und Projektleiter bei ihrer Arbeit. Zudem repräsentiere ich die Fachschaft gegenüber anderen Fachschaften, der Hochschule und nach außen."},
  { name: "Michelle",               level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Stellvertretende Geschäftsführerin",                                                       description: "Aloha! Ich bin Michelle und ich bin eure stellvertretende Geschäftsführerin. Meine Aufgabe ist es zusammen mit Florian die Fachschaft zu koordinieren. Das bedeutet ich unterstütze meine Koordinatoren, Referenten und Projektleiter bei ihrer Arbeit und schaue ob alles nach Plan läuft. Des Weiteren vertrete ich die Fachschaft gegenüber der Fakultät, der Hochschule und anderen Fachschaften.Du möchtest auch gerne in der Fachschaft aktiv sein, meld dich einfach bei mir!"},
  { name: "Thea",                   level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Referentin für Information und Publikation",                                               description: "Hallo zusammen! Ich bin Thea, eure Referentin für Information und Publikation. Ich kümmere mich um die Homepage und unsere Facebookseite, damit Du immer auf dem aktuellsten Stand in puncto Studium bist. Außerdem überarbeite ich unsere Infohefte (wie z.B. das Erstsemesterinfo). Bemerkst Du, dass Informationen nicht aktuell sind oder fehlen, kontaktiere mich einfach."},
  { name: "Paul",                   level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Koordinator für Finanzen und Projektleiter für den Umzug in den Sammelbau Maschinenwesen", description: "Hallo zusammen, ich bin Paul. Als Koordinator für Finanzen sorge ich dafür, dass die Gelder der Fachschaft verantwortungsbewusst und sachgemäß eingesetzt werden. Ich kümmere mich um die Buchhaltung, die Steuer und natürlich auch um das eigentliche Ausgeben. Wenn ihr dazu Fragen habt, dann schreibt mir einfach an finanzen@fsmb.rwth-aachen.de. Als Projektleiter für den Umzug soll ich eigentlich den Umzug der Fachschaft in den Sammelbau Maschinenwesen vorbereiten, planen und umsetzen, aber was das Umsetzen angeht, bin ich immer noch höchst skeptisch, dass es in dieser Legislaturperiode passieren wird. Falls ihr Fragen zum Sammelbau oder zum Umzug habt oder falls ihr Vorschläge für die Neuausstattung des Sammelbaus und der dortigen Lernräume machen wollt, schreibt mir einfach an umzug@fsmb.rwth-aachen.de."},
  { name: "Tim",                    level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Koordinator für Lehre und Referent für Maschinenbau",                                      description: "Hallo, mein Name ist Tim, ich studiere Maschinenbau und bin im Ratsjahr 2019/20 euer Koordinator für Lehre und Referent für Maschinenbau. Ich kümmere mich um eure Fragen zur allgemeinen Lehre und beschäftige mich mit allen Themen rund um das Maschinenbaustudium. Außerdem vertrete ich euch in einigen Fakultätsgremien. Falls ihr also Fragen zu eurem Studium allgemein oder zum Maschinenbau habt, dann zögert nicht! Schreibt mir eine E-Mail oder kommt in den Sprechstunden der Fachschaft vorbei."},
  { name: "Tom",                    level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Referent für Wirtschaftsingenieurwesen",                                                   description: "Hey, ich bin Tom und Referent für Lehre im Wirtschaftsingenieurwesen. Vor allem werde ich für Eure Fragen und Probleme in Bezug auf Euer Studium zur Verfügung stehen, zusätzlich werde ich Eure Interessen, etwa im Prüfungsausschuss, vertreten. Wenn Ihr also Hilfe benötigt, schreibt mir eine Mail oder kommt direkt zur Sprechstunde in Eurer Fachschaft."},
  { name: "Simon",                  level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Referent für Computational Engineering Science",                                           description: "Hey, mein Name ist Simon ich studiere Computational Engineering Science und ich bin diese Jahr auch der passende Referent. Ich kümmere mich um eure Fragen CES betreffend und vertrete euch in einigen Hochschulgremien. Falls ihr also Fragen zu eurem Studium habt dann zögert nicht! Schreibt mir eine E-Mail oder kommt in den Sprechstunden der Fachschaft vorbei."},
  { name: "Matthias",               level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Referent für Auslandsangelegenheiten",                                                     description: "Hallo Reisende, ich bin Matthias, Referent für Auslandsangelegenheiten. Wer hat nicht schon einmal davon geträumt, eine Reise in die weite Welt zu unternehmen? Würdest Du gerne unter Palmen liegen und ein kühles Getränk genießen, während Du in einem Skript blätterst? Ja? Dann lass Dich in der Sprechstunde über die Möglichkeiten, Dein Auslandaufenthalt zu gestalten, informieren. Du kommst von weit her? In meinen Zuständigkeitsbereich fällt auch die Betreuung von ausländischen Studierenden. Gerne beantworte ich Deine Fragen und gebe Dir Tipps für Deine Zeit in Aachen. Schreib mir einfach."},
  { name: "Lennard",                level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Koordinator für das Inventar und 2. Koordinator für Finanzen",                             description: "Hey, ich bin Lenny, Maschi im 2. Semester und in diesem Jahr Koordinator für Inventar sowie stellvertretender Koordinator für Finanzen. Als Inventarist bin ich für das Eigentum der Fachschaft verantwortlich, insbesondere den Verleih. Wenn ihr Werkzeug, Bierzeltgarnituren oder sonst was braucht, meldet euch bei mir! Für Studis ist der Verleih auch komplett kostenlos!"},
  { name: "Timo",                   level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Koordinator für die Veranstaltungen",                                                      description: "Moin Moin Maschi, dieses Jahr bin ich dein Koordinator für Veranstaltungen. Das heißt, wenn Du eine Idee für ein Event oder Lust hast eins zu organisieren, dann bin ich Dein Ansprechpartner. Ich habe mir viel vorgenommen und ich hoffe ich sehe Dich bei der ein oder anderen meiner Veranstaltungen."},
  { name: "Charlotte",              level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Referentin für Erstsemesterarbeit",                                                        description: "Hey! Mein Name ist Charlotte und ich bin dieses Jahr eure Referentin für Erstsemesterarbeit. In dieser Funktion organisiere ich die Sommer- und Wintererstsemesterzeit 2019, das Tutorenwochenende und das Erstiwochenende. Ich leite die Ersti AG, kümmere mich um die Tutoren und gebe mein Bestes den neuen Erstsemestern einen guten Start ins Studienleben zu ermöglichen. Falls ihr Fragen oder Anregungen habt, schreibt mir eine Mail oder kommt in der Fachschaft vorbei."},
  { name: "Karl",                   level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Referent für den Austausch",                                                               description: "Hallo, ich bin Karl und studiere seit zwei Jahren Maschinenbau! In diesem Ratsjahr kümmere ich mich um den Austausch nach Polen und in die Ukraine. Letztes Jahr war ich selbst in der Ukraine und habe dort viele Leute kennengelernt, u.a. Tschernobyl besucht und einfach eine unvergessliche Zeit gehabt! Wenn ihr etwas über den Austausch (oder mich) wissen wollt, könnt ihr euch jederzeit bei mir per Mail melden oder mich einfach persönlich ansprechen!"},
  { name: "Mariano",                level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Referent für Sportveranstaltungen",                                                        description: "Hey Leute, ich bin Mariano und dieses Jahr euer Sportreferent. Zu meinen Aufgaben gehören natürlich der Uni-Cup im Dezember und das Drachenbootrennen, aber auch alle anderen mit Sport zusammenhängende Veranstaltungen. Wenn ihr Anregungen für neue Events habt, euch in irgendeiner Form beteiligen wollt, oder sonst Fragen und Wünsche habt meldet euch gerne bei mir."},
  { name: "Louise",                 level: Level.find_by( rank: 2), points: 10, category: :catch, repeat_time: nil, start_date: nil, picture: nil, info: "Projektleiterin für die Erstsemesterfeier 2019",                                           description: "Hi, mein Name ist Lou und ich bin die diesjährige Veranstalterin der alljährlich besten Party des                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Semesters: der Maschi-Party. Falls ihr Ideen oder auch Wünsche bezüglich der Party habt, meldet euch bei mir und ich werde sehen was sich machen lässt Bis dahin, Tschö wa!"},
  { name: "Tierpark",               level: Level.find_by( rank: 5), points: 10, category: :place, repeat_time: nil, start_date: nil, picture: nil, info: "Besuche unser Fachschaftsmasskotchen",                                                     description: ""},
])

Group.create!([
  {name: "Einhörner", join_token: "f9EwJg3i3Wg853uzENvR9FUw", level: Level.find_by(rank: 3), points: 100, num_catches: 3, num_places: 1, num_sponsors: 2, time_together: 40},
  {name: "Eichhörnchen", join_token: "y7ixkbExLUJQwqEzmdZL7MRF", level: Level.find_by(rank: 0), points: 0, num_catches: 0, num_places: 0, num_sponsors: 0, time_together: 0},
  {name: "Einhörnchen", join_token: "tKBnZa5c9S9wuGCGTLX42qD7", level: Level.find_by(rank: 0), points: 0, num_catches: 0, num_places: 0, num_sponsors: 0, time_together: 0}
])

User.create!([
  {group_id: 1, name: "Knut", info: "Toller Hecht", picture: nil, auth_token: "Le2TJZmfq5jigu6A8k5zC39j"},
  {group_id: 1, name: "Ben", info: "Hat zwei grüne Daumen", picture: nil, auth_token: "7AoV1M3zP1rAnZ4MEp48WcPb"},
  {group_id: 1, name: "Tim", info: "Musste es mit dem Info Text völlig übertreiben, so dass dieser drei Zeilen lang sein sollte", picture: nil, auth_token: "WtGH2refK8fPx2LuSVfSfcAF"},
  {group_id: 1, name: "Lisa", info: nil, picture: nil, auth_token: "jUvponZC9t6P29ySsW3RDBCS"},
  {group_id: 1, name: "Lisa", info: nil, picture: nil, auth_token: "VrFcBs64ymij31tmyKXja3vA"},
  {group_id: 1, name: "Eva Maria", info: nil, picture: nil, auth_token: "8wQNEdcs8JRzH3JzGhsqBzQ1"},
  {group_id: 1, name: "Dieter", info: nil, picture: nil, auth_token: "hbEsoyRh8y63nH6Vw9FpYKyp"},
  {group_id: 2, name: "Harald", info: nil, picture: nil, auth_token: "i4XpMWHZCvcNwQ87VfuZX5ZG"},
  {group_id: 2, name: "Peter", info: nil, picture: nil, auth_token: "SAhjDav2RkJGM2tCERvXB8Ee"},
  {group_id: 1, name: "Hansi", info: nil, picture: nil, auth_token: "uQ2ytCN3y3HUGCh6LxQNDPzD"},
  {group_id: 1, name: "Herbert", info: nil, picture: nil, auth_token: "QDgXcgo1JD8AaPfE5Qv3TrZo"},
  {group_id: 1, name: "Andreas Arthur Eugen Albert", info: nil, picture: nil, auth_token: "SuvCaLe3RihWTAp3P63tJfjk"},
  {group_id: 1, name: "Dieter", info: nil, picture: nil, auth_token: "YSdBkVXCYMaJZAwW9DsrTmH6"}
])

RallyeStation.create!([
  {name: "Schwimmnudelziehen"},
  {name: "1, 2 oder 3"},
  {name: "Hüpfburg"},
  {name: "Jenga Schwerelos"},
  {name: "Tic Tac Toe"}
])

RallyeStation.all.each do |station|
  for points in 1..10
    RallyeRating.create! rallye_station: station, points: points
  end
end
