class Hashtag < ApplicationRecord
  has_and_belongs_to_many :photos
  enum category: [ :catch, :sponsor, :place ]

  belongs_to :level, optional: true
  belongs_to :required_by_level, optional: true, class_name: "Level"

  validate :not_required_before_available

  def not_required_before_available
    return unless self.required_by_level

    errors.add(:required_by_level, "must be greater than or equal to level (Hashtag #{self.name})") unless
    self.required_by_level.rank >= self.rank
  end

  def rank
    level&.rank || 0
  end

  def to_s
    self.name
  end

  def self.seed
    seeds = [
      # { name: "TutorenBild",             level:  Level.find_by(rank: 0), points: 0,  category: nil,    repeat_time: nil,  required_by_level: Level.find_by(rank: ),  start_date: nil, picture: 'TutorenBild.jpg',         info: "Bild von deinen Tutoren",                                                                     description: "Bestenfalls haben deine Tutoren schon ein Bild von sich hochgeladen bevor ihr eure Gruppe sucht. Anderenfalls müsst ihr sie Suchen und ein Bild von ihnen Machen. Es sind nur die Tutoren auf diesem Bild nötig, die Mindestanzahl von 3 Personen pro Bild gilt hier nicht. "},
      {   name: "GruppenBild",             level:  Level.find_by(rank: 1), points: 50, category: nil,    repeat_time: nil,  required_by_level: Level.find_by(rank: 1), start_date: nil, picture: nil,                       info: "Macht ein Bild von eurer Gruppe",                                                             description: "Je ausgefallener die Bilder sind, desto besser. Sorgt bei gerade beim Gruppenbild dafür, dass alle eure Teammitglieder auf dem Bild sind. Abgesehen von genannten Ausnahmen müssen auf allen Bildern mindestens 3 Teammitglieder zu sehen sein. Ein späteres Hochladen der Bilder aus der Erstiwoche ist für Späteinsteiger möglich. Verlinkt dafür jeweils die passenden Hashtags. "},
      {   name: "PinguinStatue",           level:  Level.find_by(rank: 2), points: 0,  category: nil,    repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Sammelt möglichst viele Dosen",                                                               description: "Aus diesen Dosen bastelt ihr die größt mögliche Pinguin Statue. Lasst euch ruhig den ganzen Monat dafür Zeit. Die Punkte werden am Ende von einem Team hochqualifizierter Pinguinexperten vergeben."},
      {   name: "Essen",                   level:  Level.find_by(rank: 2), points: 10, category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 3), start_date: nil, picture: nil,                       info: "Gemeinsames Essen oder Kochen",                                                               description: "Wiederholbar; Bekocht euch gegenseitig oder geht gemeinsam in die Mensa."},
      {   name: "Spielen",                 level:  Level.find_by(rank: 2), points: 10, category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 4), start_date: nil, picture: 'Spielen.jpg',             info: "Spielt IRGENDEIN Spiel zusammen",                                                             description: "Wiederholbar; z.B. Spielefiebel S. 48: Hühnerkampf."},
      {   name: "SuperC",                  level:  Level.find_by(rank: 2), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      {   name: "Hauptgebäude",            level:  Level.find_by(rank: 2), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      {   name: "Kármán-Tor",              level:  Level.find_by(rank: 2), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: "Geht auf keinen Fall durch das Tor hindurch!"},
      {   name: "Schmachtenburg",          level:  Level.find_by(rank: 2), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      {   name: "Ponttor",                 level:  Level.find_by(rank: 2), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      # { name: "Institutsführung",        level:  Level.find_by(rank: 2), points: 40, category: nil,    repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Geht auf jeden Fall zu der Institutsführung die euch zugeteilt ist. ",                        description: "Die Institute machen sich extra Arbeit nur um euch die Institute zu zeigen also nehmt diesen Termin mit allen Gruppenmitgliedern wahr."},
      # { name: "GrillplatzRütscherstraße",level:  Level.find_by(rank: 3), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto an diesem Ort",                                                                description: ""},
      {   name: "Unicup",                  level:  Level.find_by(rank: 2), points: 20, category: nil,    repeat_time: 3600, required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Geht zu den Auswahltrainings",                                                                description: "Egal wie viel ihr denkt zu können, traut euch zu den Auswahltrainings. Es ist keine Schande nicht ins Team zu kommen, aber ihr werdet euch immer ärgern es nicht versucht zu haben."},
      {   name: "Tutorenversorgung",       level:  Level.find_by(rank: 3), points: 10, category: nil,    repeat_time: 3600, required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Versorgt eure Tutoren mit Getränken",                                                         description: "Wiederholbar; Ihr könnt euch bei euren Tutoren jederzeit mit einem Kalt oder Warmgetränk für ihre Expertise im Stadt kennenlernen bedanken"},
      {   name: "Rathaus",                 level:  Level.find_by(rank: 3), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      {   name: "Dom",                     level:  Level.find_by(rank: 3), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Dom.jpg',                 info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      {   name: "HennigsHorde",            level:  Level.find_by(rank: 3), points: 3,  category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 3), start_date: nil, picture: 'HennigsHorde.jpg',        info: "Findet so viele Horde-Sticker wie möglich",                                                   description: "Wiederholbar; Lustige Gruppenbilder gemeinsam mit den Stickern& erkennbaren Ort des Stickers sind die besten Bilder. Die Mindestanzahl von 3 Personen pro Bild gilt hier nicht. "},
      {   name: "EtiSticker",              level:  Level.find_by(rank: 4), points: 5,  category: nil,    repeat_time: 3600, required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Entfernt die blauen kleinen Eti-Sticker",                                                     description: "Wiederholbar; Lustige Gruppenbilder gemeinsam mit dem Sticker und erkennbarem Ort des Stickers sind die besten Bilder. Die Mindestanzahl von 3 Personen pro Bild gilt hier nicht. "},
      {   name: "MediSticker",             level:  Level.find_by(rank: 4), points: 5,  category: nil,    repeat_time: 3600, required_by_level: nil,                    start_date: nil, picture: 'MediSticker.jpg',         info: "Entfernt die grünen runden Medi-Sticker",                                                     description: "Wiederholbar; Lustige Gruppenbilder gemeinsam mit dem Sticker und erkennbarem Ort des Stickers sind die besten Bilder. Die Mindestanzahl von 3 Personen pro Bild gilt hier nicht. "},
      # { name: "RWTHOnlineSchulung",      level:  Level.find_by(rank: 2), points: 20, category: nil,    repeat_time: nil , required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Besucht eure Schulungen",                                                                     description: "Die Schulungen sind sehr hilfreich um sich in den Onlinesystemen auszukennen. Inhalt ist Klausurrelevant!!"},
      {   name: "Natur",                   level:  Level.find_by(rank: 4), points: 10, category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 4), start_date: nil, picture: 'Natur.jpg',               info: "Geht mal in die Natur.",                                                                      description: "Wiederholbar; Erkundet die Grünflächen in und um Aachen. Aber hinterlasst keinen Müll und benehmt euch"},
      {   name: "Pyjamaparty",             level:  Level.find_by(rank: 4), points: 20, category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 7), start_date: nil, picture: nil,                       info: "Übernachtet gemeinsam irgendwo.",                                                             description: "Wiederholbar; Egal ob jemand noch keine Wohnung hat, zu weit weg wohnt und ihr ihm einen Schlafplatz bietet oder ihr eine Sleepoverparty macht."},
      {   name: "AusSicherheitsgründen",   level:  Level.find_by(rank: 4), points: 10, category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 5), start_date: nil, picture: nil,                       info: "Überall wo man das sagen Kann",                                                               description: "Wiederholbar; Macht etwas wozu man sagen kann \"aus Sicherheitsgründen\". Jemanden Abends heim bringen, beim Fahrradfahren Warnwesten und Helm tragen... werdet kreativ"},
      {   name: "Humba",                   level:  Level.find_by(rank: 4), points: 10, category: nil,    repeat_time: 3600, required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Gesänge anstimmen",                                                                           description: "Ob Humba oder ein anderes freundliches Lied, ihr könnt an dieser Stelle alles Singen."},
      {   name: "MüllAufheben",            level:  Level.find_by(rank: 4), points: 10, category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 5), start_date: nil, picture: nil,                       info: "Macht es besser als die vor euch und Entfernt Müll",                                          description: "Wiederholbar; Damit nicht nur die Fachschaft, das ESA- Team und die Stadt euch hinterherräumen werdet selber mal aktiv und hinterlasst die Orte wo ihr wart sauberer als vorher."},
      {   name: "KostümGehtImmer",         level:  Level.find_by(rank: 2), points: 20, category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 7), start_date: nil, picture: nil,                       info: "Überlegt euch ein Gruppenkostüm/Motto",                                                       description: "Wiederholbar; In einer Gruppe ein Kostüm tragen wirkt Wunder beim Gruppenzusammenhalt und ihr sorgt für eine allgemein verbesserte Stimmung, wenn ihr so auf einer Veranstaltung/Party auftaucht."},
      {   name: "SeidAktiv",               level:  Level.find_by(rank: 5), points: 20, category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 6), start_date: nil, picture: nil,                       info: "Informiert euch über Aachens soziale Gruppen",                                                description: "Wiederholbar; Informiert euch über die diversen sozial engagierte Gruppen in Aachen und geht zu mindestens einer der vielen Öffentlichen Informationsveranstalungen. Neben der Fachschaft gibt es massig Gruppen in denen man immer nette Leute Treffen kann und auf verscheidene weise aktiv werden kann. Nur um einige beispiele zu nennen: die Jugendgruppen der Parteien, sowie die Studierenparlament Gruppen, andere studentische Gruppen (wie das Rennsportteam), Fridays for Futher, Aachen Unverpackt, Foodsharing Aachen... Unter dem Stichwort \"Kritische Einführungswoche Aachen\" solltet ihr ein paar weitere Ideen bekommen"},
      {   name: "LebtBewusst",             level:  Level.find_by(rank: 6), points: 20, category: nil,    repeat_time: 10,   required_by_level: Level.find_by(rank: 6), start_date: nil, picture: nil,                       info: "Rechnet eure CO2 Bilanz aus",                                                                 description: "Wiederholbar für jeden einmal; Rechnet mal eure CO2 Bilanz aus, je mehr es euch interessiert desto datailierter und vergleicht sie mit 2000kg maximum im Durchschnitt pro Person um die Klimaziele zu erreichen. Vergesst euren letzten Urlaub nicht und auch nicht den den ihr grade im Geiste plant."},
      {   name: "VollerFarbkreis",         level:  Level.find_by(rank: 3), points: 10, category: nil,    repeat_time: 3600, required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Macht Bilder mit den verschiedenfarbigen Tutoren anderer Fachschaften und Anderer Jahrgänge", description: "Wiederholbar; Findet im Rahmen der Erstiwoche und auch danach so viele Farben der verschiedenen Fachschaften und Jahre wie möglich. Für jede Farbe/Jahrgang kann ein Bild gemacht werden. Die Mindestanzahl von 3 Personen pro Bild gilt nur innerhalb der Erstiwoche, anschließend dürft ihr die Leute auch alleine nach einem Foto fragen."},
      {   name: "Asta",                    level:  Level.find_by(rank: 3), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      {   name: "MaschiPartySchlange",     level:  Level.find_by(rank: 3), points: 30, category: nil,    repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Ist für jeden Maschi ein muss",                                                               description: "Wenn ihr dann noch rein kommt um so besser."},
      {   name: "KaterTag",                level:  Level.find_by(rank: 3), points: 10, category: nil,    repeat_time: 3600, required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Geteiltes Leid ist halbes Leid",                                                              description: "Wiederholbar; Verbringt den Tag, an dem ihr euch von den Strapazen der anstrengenden Woche erholt habt gemeinsam. Top Auswahl an Filmen sind \"Findet Nemo\" und \"Frozen\""},
      {   name: "Gratis",                  level:  Level.find_by(rank: 4), points: 5,  category: nil,    repeat_time: 3600, required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Teilt eurem Team mit, wenn es was umsonst gibt",                                               description: "Wiederholbar; Wenn Erstitüten verteilt werden, oder es sonst etwas kostenlos gibt."},
      {   name: "Mensa",                   level:  Level.find_by(rank: 4), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      {   name: "Fachschaft",              level:  Level.find_by(rank: 4), points: 20, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Fachschaft.jpg',          info: "Mache ein Foto in der Fachschaft",                                                            description: ""},
      {   name: "Bushof",                  level:  Level.find_by(rank: 3), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      {   name: "UKA",                     level:  Level.find_by(rank: 4), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      {   name: "Theater",                 level:  Level.find_by(rank: 4), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto mit dem Gebäude",                                                              description: ""},
      {   name: "HängemattenLousberg",     level:  Level.find_by(rank: 5), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto an diesem Ort",                                                                description: ""},
      {   name: "3-LänderEck",             level:  Level.find_by(rank: 5), points: 10, category: :place, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Mache ein Foto an diesem Ort",                                                                description: ""},
      {   name: "Blutspenden",             level:  Level.find_by(rank: 4), points: 20, category: nil,    repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Blut ist immer eine Mangelware",                                                              description: "Geht gemeinsam mit eurer Gruppe regelmäßig Blutspenden. Dadurch erinnert ihr euch gegenseitig daran und ihr geht öfter."},
      {   name: "Hüpfen",                  level:  Level.find_by(rank: 5), points: 10, category: nil,    repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Besucht den Beliebtesten Kurs im HSZ",                                                        description: "Erfahrt durch die Buchung und Besuchung des Kurses \"Fitness mit Musik\" den Ablauf eines Sportkurses. Informiert euch über das vielfältige Sportangebot des Hoschschul Sport Zentrums"},
      {   name: "KuchenFürCharlotte",      level:  Level.find_by(rank: 5), points: 50, category: nil,    repeat_time: nil,  required_by_level: Level.find_by(rank: 8), start_date: nil, picture: nil,                       info: "Heute ist Charlottes Geburstag",                                                              description: "Bringt ihr möglichst bald einen Kuchen in die Fachschaft und bedankt euch für ihre Arbeit in der Erstiwoche. Kuchen geht zu jeder Mahlzeit."},
      {   name: "Florian",                 level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Florian.jpg',             info: "Geschäftsführer",                                                                             description: "Hey Maschis, mein Name ist Florian und am liebsten lasse ich mich wie Majästätix durch die Gegend tragen. Man kennt mich womöglich schon aus dem letzten Fachschaftsrat, welcher mir super Spaß gemacht hat. Da hatte ich direkt Lust auf die zweite Runde, nun als euer Geschäftsführer für das Ratsjahr 2019/2020. Meine Aufgabe ist es, die Abläufe in der Fachschaftsarbeit zu koordinieren. Dafür unterstütze ich meine Koordinatoren, Referenten und Projektleiter bei ihrer Arbeit. Zudem repräsentiere ich die Fachschaft gegenüber anderen Fachschaften, der Hochschule und nach außen."},
      {   name: "Michelle",                level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Michelle.jpg',            info: "Stellvertretende Geschäftsführerin",                                                          description: "Aloha! Ich bin Michelle und ich bin eure stellvertretende Geschäftsführerin. Meine Aufgabe ist es zusammen mit Florian die Fachschaft zu koordinieren. Das bedeutet ich unterstütze meine Koordinatoren, Referenten und Projektleiter bei ihrer Arbeit und schaue ob alles nach Plan läuft. Des Weiteren vertrete ich die Fachschaft gegenüber der Fakultät, der Hochschule und anderen Fachschaften.Du möchtest auch gerne in der Fachschaft aktiv sein, meld dich einfach bei mir!"},
      {   name: "Thea",                    level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Thea.jpg',                info: "Referentin für Information und Publikation",                                                  description: "Hallo zusammen! Ich bin Thea, eure Referentin für Information und Publikation. Ich kümmere mich um die Homepage und unsere Facebookseite, damit Du immer auf dem aktuellsten Stand in puncto Studium bist. Außerdem überarbeite ich unsere Infohefte (wie z.B. das Erstsemesterinfo). Bemerkst Du, dass Informationen nicht aktuell sind oder fehlen, kontaktiere mich einfach."},
      {   name: "Paul",                    level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Paul.jpg',                info: "Koordinator für Finanzen und Projektleiter für den Umzug in den Sammelbau Maschinenwesen",    description: "Hallo zusammen, ich bin Paul. Als Koordinator für Finanzen sorge ich dafür, dass die Gelder der Fachschaft verantwortungsbewusst und sachgemäß eingesetzt werden. Ich kümmere mich um die Buchhaltung, die Steuer und natürlich auch um das eigentliche Ausgeben. Wenn ihr dazu Fragen habt, dann schreibt mir einfach an finanzen@fsmb.rwth-aachen.de. Als Projektleiter für den Umzug soll ich eigentlich den Umzug der Fachschaft in den Sammelbau Maschinenwesen vorbereiten, planen und umsetzen, aber was das Umsetzen angeht, bin ich immer noch höchst skeptisch, dass es in dieser Legislaturperiode passieren wird. Falls ihr Fragen zum Sammelbau oder zum Umzug habt oder falls ihr Vorschläge für die Neuausstattung des Sammelbaus und der dortigen Lernräume machen wollt, schreibt mir einfach an umzug@fsmb.rwth-aachen.de."},
      {   name: "Tim",                     level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Tim.jpg',                 info: "Koordinator für Lehre und Referent für Maschinenbau",                                         description: "Hallo, mein Name ist Tim, ich studiere Maschinenbau und bin im Ratsjahr 2019/20 euer Koordinator für Lehre und Referent für Maschinenbau. Ich kümmere mich um eure Fragen zur allgemeinen Lehre und beschäftige mich mit allen Themen rund um das Maschinenbaustudium. Außerdem vertrete ich euch in einigen Fakultätsgremien. Falls ihr also Fragen zu eurem Studium allgemein oder zum Maschinenbau habt, dann zögert nicht! Schreibt mir eine E-Mail oder kommt in den Sprechstunden der Fachschaft vorbei."},
      {   name: "Tom",                     level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Tom.jpg',                 info: "Referent für Wirtschaftsingenieurwesen",                                                      description: "Hey, ich bin Tom und Referent für Lehre im Wirtschaftsingenieurwesen. Vor allem werde ich für Eure Fragen und Probleme in Bezug auf Euer Studium zur Verfügung stehen, zusätzlich werde ich Eure Interessen, etwa im Prüfungsausschuss, vertreten. Wenn Ihr also Hilfe benötigt, schreibt mir eine Mail oder kommt direkt zur Sprechstunde in Eurer Fachschaft."},
      {   name: "Simon",                   level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Simon.jpg',               info: "Referent für Computational Engineering Science",                                              description: "Hey, mein Name ist Simon ich studiere Computational Engineering Science und ich bin diese Jahr auch der passende Referent. Ich kümmere mich um eure Fragen CES betreffend und vertrete euch in einigen Hochschulgremien. Falls ihr also Fragen zu eurem Studium habt dann zögert nicht! Schreibt mir eine E-Mail oder kommt in den Sprechstunden der Fachschaft vorbei."},
      {   name: "Matthias",                level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Matthias.jpg',            info: "Referent für Auslandsangelegenheiten",                                                        description: "Hallo Reisende, ich bin Matthias, Referent für Auslandsangelegenheiten. Wer hat nicht schon einmal davon geträumt, eine Reise in die weite Welt zu unternehmen? Würdest Du gerne unter Palmen liegen und ein kühles Getränk genießen, während Du in einem Skript blätterst? Ja? Dann lass Dich in der Sprechstunde über die Möglichkeiten, Dein Auslandaufenthalt zu gestalten, informieren. Du kommst von weit her? In meinen Zuständigkeitsbereich fällt auch die Betreuung von ausländischen Studierenden. Gerne beantworte ich Deine Fragen und gebe Dir Tipps für Deine Zeit in Aachen. Schreib mir einfach."},
      {   name: "Lennard",                 level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Lennard.jpg',             info: "Koordinator für das Inventar und 2. Koordinator für Finanzen",                                description: "Hey, ich bin Lenny, Maschi im 2. Semester und in diesem Jahr Koordinator für Inventar sowie stellvertretender Koordinator für Finanzen. Als Inventarist bin ich für das Eigentum der Fachschaft verantwortlich, insbesondere den Verleih. Wenn ihr Werkzeug, Bierzeltgarnituren oder sonst was braucht, meldet euch bei mir! Für Studis ist der Verleih auch komplett kostenlos!"},
      {   name: "Timo",                    level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Timo.jpg',                info: "Koordinator für die Veranstaltungen",                                                         description: "Moin Moin Maschi, dieses Jahr bin ich dein Koordinator für Veranstaltungen. Das heißt, wenn Du eine Idee für ein Event oder Lust hast eins zu organisieren, dann bin ich Dein Ansprechpartner. Ich habe mir viel vorgenommen und ich hoffe ich sehe Dich bei der ein oder anderen meiner Veranstaltungen."},
      {   name: "Charlotte",               level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Charlotte.jpg',           info: "Referentin für Erstsemesterarbeit",                                                           description: "Hey! Mein Name ist Charlotte und ich bin dieses Jahr eure Referentin für Erstsemesterarbeit. In dieser Funktion organisiere ich die Sommer- und Wintererstsemesterzeit 2019, das Tutorenwochenende und das Erstiwochenende. Ich leite die Ersti AG, kümmere mich um die Tutoren und gebe mein Bestes den neuen Erstsemestern einen guten Start ins Studienleben zu ermöglichen. Falls ihr Fragen oder Anregungen habt, schreibt mir eine Mail oder kommt in der Fachschaft vorbei."},
      {   name: "Karl",                    level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Karl.jpg',                info: "Referent für den Austausch",                                                                  description: "Hallo, ich bin Karl und studiere seit zwei Jahren Maschinenbau! In diesem Ratsjahr kümmere ich mich um den Austausch nach Polen und in die Ukraine. Letztes Jahr war ich selbst in der Ukraine und habe dort viele Leute kennengelernt, u.a. Tschernobyl besucht und einfach eine unvergessliche Zeit gehabt! Wenn ihr etwas über den Austausch (oder mich) wissen wollt, könnt ihr euch jederzeit bei mir per Mail melden oder mich einfach persönlich ansprechen!"},
      {   name: "Mariano",                 level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Mariano.jpg',             info: "Referent für Sportveranstaltungen",                                                           description: "Hey Leute, ich bin Mariano und dieses Jahr euer Sportreferent. Zu meinen Aufgaben gehören natürlich der Uni-Cup im Dezember und das Drachenbootrennen, aber auch alle anderen mit Sport zusammenhängende Veranstaltungen. Wenn ihr Anregungen für neue Events habt, euch in irgendeiner Form beteiligen wollt, oder sonst Fragen und Wünsche habt meldet euch gerne bei mir."},
      {   name: "Louise",                  level:  Level.find_by(rank: 3), points: 10, category: :catch, repeat_time: nil,  required_by_level: nil,                    start_date: nil, picture: 'Louise.jpg',              info: "Projektleiterin für die Erstsemesterfeier 2019",                                              description: "Hi, mein Name ist Lou und ich bin die diesjährige Veranstalterin der alljährlich besten Party des Semesters: der Maschi-Party. Falls ihr Ideen oder auch Wünsche bezüglich der Party habt, meldet euch bei mir und ich werde sehen was sich machen lässt Bis dahin, Tschö wa!"},
      {   name: "Tierpark",                level:  Level.find_by(rank: 6), points: 10, category: :place, repeat_time: nil,  required_by_level: Level.find_by(rank: 9), start_date: nil, picture: 'Tierpark.jpg',            info: "Besuche unser Fachschaftsmaskottchen",                                                        description: "Quizfrage: Wie viele Pinguine stehen links von Henning?"},
      {   name: "Vorlesung",               level:  Level.find_by(rank: 2), points: 20, category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 2), start_date: nil, picture: nil,                       info: "Besucht gemeinsam eine Vorlesung",                                                            description: "Wiederholbar; Gespräche und Papierfliegerwettbewerbe hindern euch am einschlafen. Außerdem passen mehr Leute in den Hörsaal, wenn nicht jeder aus Anstand links und rechts einen Platz frei lässt."},
      {   name: "Übung",                   level:  Level.find_by(rank: 2), points: 20, category: nil,    repeat_time: 3600, required_by_level: Level.find_by(rank: 3), start_date: nil, picture: nil,                       info: "Besucht gemeinsam eine Übung",                                                                description: "Wiederholbar; Egal ob Kleingruppenübung oder Tutorium, auch hier ist Gesellschaft erwünscht." },
      {   name: "Lerngruppe",              level:  Level.find_by(rank: 2), points: 15, category: nil,    repeat_time: 3600, required_by_level: nil,                    start_date: nil, picture: 'Tierpark.jpg',            info: "Bildet eine Lerngruppe",                                                                      description: "Wiederholbar; Trefft euch zu Hause, im Audimax Keller oder in einem der anderen vielen Lernräume und unterstützt euch gegenseitig dabei. "},
      {   name: "SchneeBallEffekt",        level:  Level.find_by(rank: 3), points: 50, category: nil,    repeat_time: 3600, required_by_level: nil,                    start_date: nil, picture: nil,                       info: "Bringe jemanden dazu das Erstigame zu spielen",                                               description: "Wiederholbar; Motivert eine neue Gruppe dazu das Erstigame zu spielen. Als Beweis müsst ihr ein Bild von der Startseite der angeworbenen Gruppe nach dem Einsenden des Gruppenbilds machen. Sollten sie keine Tutorengruppe sein, die ohnehin einen Einladungslink hat, kann auf der Registrierungsseite eine neue Gruppe erstellt werden. Die Mindestanzahl von 3 Personen pro Bild gilt hier nicht."},
    ]

    seeds.each do |seed|
      hashtag = self.find_by name: seed[:name]
      hashtag&.update seed

      self.create(seed) unless hashtag
    end
  end

end
